# Generated by Django 3.0.10 on 2024-12-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlalias',
            name='name',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
